window.SAMPLE_CATALOGUE_DATA = {
  "source": "sample-data / contract daily rates only",
  "updatedAt": "2026-06-10T10:20:24.538943Z",
  "count": 18,
  "rows": [
    {
      "Record ID": "CAT-001",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Aleph Doha Residences, Curio Collection by Hilton",
      "Category": "Hotel / Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Short Stay",
      "Season": "All Year",
      "Valid Dates": "01 Jan 2026 – 31 Dec 2026",
      "Season Start": "2026-01-01",
      "Season End": "2026-12-31",
      "Room Type": "Sky Guest Room City View",
      "Bedrooms": "",
      "View": "City View",
      "Single Occupancy Rate QAR": 450,
      "Double Occupancy Rate QAR": 500,
      "Daily Rate QAR": 450,
      "Rate Basis": "Per room, per night; transient business travel only up to 9 rooms/night",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Breakfast; 0% VAT subject to change; no commission; daily housekeeping for short stays; 24-hour maintenance and room service; gym access on 1st floor; indoor pool access on 52nd floor; all rooms subject to availability; confidential corporate rate; not valid for conference/group events or city-wide congresses/events.",
      "Additional Information / Amenities Notes": "Also includes a negotiated 10% discount off Best Available Rate for all available room types where applicable. Lunch supplement QAR 75 per person; dinner supplement QAR 75 per person; airport supplement QAR 140 per way.",
      "Supplements / Blackouts": "Eid El Fitr 19–28 Mar 2026: +QAR 250/night; Eid El Adha 25–30 May 2026: +QAR 250/night; Formula 1 26 Nov–01 Dec 2026: +QAR 350/night.",
      "Cancellation Policy": "Until 6:00 PM on arrival date: no charge. After 6:00 PM on arrival date or no-show: first night room rate plus applicable tax. House policy may change with 60 days' notice.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "Guest settles bill upon departure unless company credit/direct billing has been separately established. Payment terms may be net 30 where company credit applies.",
      "Reservation Method": "Direct to hotel",
      "Contact Name": "Reservations Team",
      "Contact Email": "Reservations.DOHAR@hilton.com",
      "Contact Phone": "+974 400 47 400",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 1,
      "Booking / Display Notes": "Verify final availability, taxes, blackout supplements, and booking requirements with the hotel before confirmation.",
      "Internal Notes": "Daily short-stay rows only. Long-stay monthly/yearly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Aleph Doha Residences (2).pdf, pp. 1-3"
    },
    {
      "Record ID": "CAT-002",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Aleph Doha Residences, Curio Collection by Hilton",
      "Category": "Hotel / Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Short Stay",
      "Season": "All Year",
      "Valid Dates": "01 Jan 2026 – 31 Dec 2026",
      "Season Start": "2026-01-01",
      "Season End": "2026-12-31",
      "Room Type": "Sky Guest Room Sea View",
      "Bedrooms": "",
      "View": "Sea View",
      "Single Occupancy Rate QAR": 500,
      "Double Occupancy Rate QAR": 550,
      "Daily Rate QAR": 500,
      "Rate Basis": "Per room, per night; transient business travel only up to 9 rooms/night",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Breakfast; 0% VAT subject to change; no commission; daily housekeeping for short stays; 24-hour maintenance and room service; gym access on 1st floor; indoor pool access on 52nd floor; all rooms subject to availability; confidential corporate rate; not valid for conference/group events or city-wide congresses/events.",
      "Additional Information / Amenities Notes": "Also includes a negotiated 10% discount off Best Available Rate for all available room types where applicable. Lunch supplement QAR 75 per person; dinner supplement QAR 75 per person; airport supplement QAR 140 per way.",
      "Supplements / Blackouts": "Eid El Fitr 19–28 Mar 2026: +QAR 250/night; Eid El Adha 25–30 May 2026: +QAR 250/night; Formula 1 26 Nov–01 Dec 2026: +QAR 350/night.",
      "Cancellation Policy": "Until 6:00 PM on arrival date: no charge. After 6:00 PM on arrival date or no-show: first night room rate plus applicable tax. House policy may change with 60 days' notice.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "Guest settles bill upon departure unless company credit/direct billing has been separately established. Payment terms may be net 30 where company credit applies.",
      "Reservation Method": "Direct to hotel",
      "Contact Name": "Reservations Team",
      "Contact Email": "Reservations.DOHAR@hilton.com",
      "Contact Phone": "+974 400 47 400",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 2,
      "Booking / Display Notes": "Verify final availability, taxes, blackout supplements, and booking requirements with the hotel before confirmation.",
      "Internal Notes": "Daily short-stay rows only. Long-stay monthly/yearly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Aleph Doha Residences (2).pdf, pp. 1-3"
    },
    {
      "Record ID": "CAT-003",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Aleph Doha Residences, Curio Collection by Hilton",
      "Category": "Hotel / Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Short Stay",
      "Season": "All Year",
      "Valid Dates": "01 Jan 2026 – 31 Dec 2026",
      "Season Start": "2026-01-01",
      "Season End": "2026-12-31",
      "Room Type": "Sky One Bedroom City View",
      "Bedrooms": 1,
      "View": "City View",
      "Single Occupancy Rate QAR": 700,
      "Double Occupancy Rate QAR": 750,
      "Daily Rate QAR": 700,
      "Rate Basis": "Per room, per night; transient business travel only up to 9 rooms/night",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Breakfast; 0% VAT subject to change; no commission; daily housekeeping for short stays; 24-hour maintenance and room service; gym access on 1st floor; indoor pool access on 52nd floor; all rooms subject to availability; confidential corporate rate; not valid for conference/group events or city-wide congresses/events.",
      "Additional Information / Amenities Notes": "Also includes a negotiated 10% discount off Best Available Rate for all available room types where applicable. Lunch supplement QAR 75 per person; dinner supplement QAR 75 per person; airport supplement QAR 140 per way.",
      "Supplements / Blackouts": "Eid El Fitr 19–28 Mar 2026: +QAR 250/night; Eid El Adha 25–30 May 2026: +QAR 250/night; Formula 1 26 Nov–01 Dec 2026: +QAR 350/night.",
      "Cancellation Policy": "Until 6:00 PM on arrival date: no charge. After 6:00 PM on arrival date or no-show: first night room rate plus applicable tax. House policy may change with 60 days' notice.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "Guest settles bill upon departure unless company credit/direct billing has been separately established. Payment terms may be net 30 where company credit applies.",
      "Reservation Method": "Direct to hotel",
      "Contact Name": "Reservations Team",
      "Contact Email": "Reservations.DOHAR@hilton.com",
      "Contact Phone": "+974 400 47 400",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 3,
      "Booking / Display Notes": "Verify final availability, taxes, blackout supplements, and booking requirements with the hotel before confirmation.",
      "Internal Notes": "Daily short-stay rows only. Long-stay monthly/yearly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Aleph Doha Residences (2).pdf, pp. 1-3"
    },
    {
      "Record ID": "CAT-004",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Aleph Doha Residences, Curio Collection by Hilton",
      "Category": "Hotel / Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Short Stay",
      "Season": "All Year",
      "Valid Dates": "01 Jan 2026 – 31 Dec 2026",
      "Season Start": "2026-01-01",
      "Season End": "2026-12-31",
      "Room Type": "Sky One Bedroom Sea View",
      "Bedrooms": 1,
      "View": "Sea View",
      "Single Occupancy Rate QAR": 750,
      "Double Occupancy Rate QAR": 800,
      "Daily Rate QAR": 750,
      "Rate Basis": "Per room, per night; transient business travel only up to 9 rooms/night",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Breakfast; 0% VAT subject to change; no commission; daily housekeeping for short stays; 24-hour maintenance and room service; gym access on 1st floor; indoor pool access on 52nd floor; all rooms subject to availability; confidential corporate rate; not valid for conference/group events or city-wide congresses/events.",
      "Additional Information / Amenities Notes": "Also includes a negotiated 10% discount off Best Available Rate for all available room types where applicable. Lunch supplement QAR 75 per person; dinner supplement QAR 75 per person; airport supplement QAR 140 per way.",
      "Supplements / Blackouts": "Eid El Fitr 19–28 Mar 2026: +QAR 250/night; Eid El Adha 25–30 May 2026: +QAR 250/night; Formula 1 26 Nov–01 Dec 2026: +QAR 350/night.",
      "Cancellation Policy": "Until 6:00 PM on arrival date: no charge. After 6:00 PM on arrival date or no-show: first night room rate plus applicable tax. House policy may change with 60 days' notice.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "Guest settles bill upon departure unless company credit/direct billing has been separately established. Payment terms may be net 30 where company credit applies.",
      "Reservation Method": "Direct to hotel",
      "Contact Name": "Reservations Team",
      "Contact Email": "Reservations.DOHAR@hilton.com",
      "Contact Phone": "+974 400 47 400",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 4,
      "Booking / Display Notes": "Verify final availability, taxes, blackout supplements, and booking requirements with the hotel before confirmation.",
      "Internal Notes": "Daily short-stay rows only. Long-stay monthly/yearly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Aleph Doha Residences (2).pdf, pp. 1-3"
    },
    {
      "Record ID": "CAT-005",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Aleph Doha Residences, Curio Collection by Hilton",
      "Category": "Hotel / Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Short Stay",
      "Season": "All Year",
      "Valid Dates": "01 Jan 2026 – 31 Dec 2026",
      "Season Start": "2026-01-01",
      "Season End": "2026-12-31",
      "Room Type": "Sky Two Bedroom City View",
      "Bedrooms": 2,
      "View": "City View",
      "Single Occupancy Rate QAR": 900,
      "Double Occupancy Rate QAR": 950,
      "Daily Rate QAR": 900,
      "Rate Basis": "Per room, per night; transient business travel only up to 9 rooms/night",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Breakfast; 0% VAT subject to change; no commission; daily housekeeping for short stays; 24-hour maintenance and room service; gym access on 1st floor; indoor pool access on 52nd floor; all rooms subject to availability; confidential corporate rate; not valid for conference/group events or city-wide congresses/events.",
      "Additional Information / Amenities Notes": "Also includes a negotiated 10% discount off Best Available Rate for all available room types where applicable. Lunch supplement QAR 75 per person; dinner supplement QAR 75 per person; airport supplement QAR 140 per way.",
      "Supplements / Blackouts": "Eid El Fitr 19–28 Mar 2026: +QAR 250/night; Eid El Adha 25–30 May 2026: +QAR 250/night; Formula 1 26 Nov–01 Dec 2026: +QAR 350/night.",
      "Cancellation Policy": "Until 6:00 PM on arrival date: no charge. After 6:00 PM on arrival date or no-show: first night room rate plus applicable tax. House policy may change with 60 days' notice.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "Guest settles bill upon departure unless company credit/direct billing has been separately established. Payment terms may be net 30 where company credit applies.",
      "Reservation Method": "Direct to hotel",
      "Contact Name": "Reservations Team",
      "Contact Email": "Reservations.DOHAR@hilton.com",
      "Contact Phone": "+974 400 47 400",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 5,
      "Booking / Display Notes": "Verify final availability, taxes, blackout supplements, and booking requirements with the hotel before confirmation.",
      "Internal Notes": "Daily short-stay rows only. Long-stay monthly/yearly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Aleph Doha Residences (2).pdf, pp. 1-3"
    },
    {
      "Record ID": "CAT-006",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Aleph Doha Residences, Curio Collection by Hilton",
      "Category": "Hotel / Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Short Stay",
      "Season": "All Year",
      "Valid Dates": "01 Jan 2026 – 31 Dec 2026",
      "Season Start": "2026-01-01",
      "Season End": "2026-12-31",
      "Room Type": "Sky Two Bedroom Sea View",
      "Bedrooms": 2,
      "View": "Sea View",
      "Single Occupancy Rate QAR": 1000,
      "Double Occupancy Rate QAR": 1050,
      "Daily Rate QAR": 1000,
      "Rate Basis": "Per room, per night; transient business travel only up to 9 rooms/night",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Breakfast; 0% VAT subject to change; no commission; daily housekeeping for short stays; 24-hour maintenance and room service; gym access on 1st floor; indoor pool access on 52nd floor; all rooms subject to availability; confidential corporate rate; not valid for conference/group events or city-wide congresses/events.",
      "Additional Information / Amenities Notes": "Also includes a negotiated 10% discount off Best Available Rate for all available room types where applicable. Lunch supplement QAR 75 per person; dinner supplement QAR 75 per person; airport supplement QAR 140 per way.",
      "Supplements / Blackouts": "Eid El Fitr 19–28 Mar 2026: +QAR 250/night; Eid El Adha 25–30 May 2026: +QAR 250/night; Formula 1 26 Nov–01 Dec 2026: +QAR 350/night.",
      "Cancellation Policy": "Until 6:00 PM on arrival date: no charge. After 6:00 PM on arrival date or no-show: first night room rate plus applicable tax. House policy may change with 60 days' notice.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "Guest settles bill upon departure unless company credit/direct billing has been separately established. Payment terms may be net 30 where company credit applies.",
      "Reservation Method": "Direct to hotel",
      "Contact Name": "Reservations Team",
      "Contact Email": "Reservations.DOHAR@hilton.com",
      "Contact Phone": "+974 400 47 400",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 6,
      "Booking / Display Notes": "Verify final availability, taxes, blackout supplements, and booking requirements with the hotel before confirmation.",
      "Internal Notes": "Daily short-stay rows only. Long-stay monthly/yearly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Aleph Doha Residences (2).pdf, pp. 1-3"
    },
    {
      "Record ID": "CAT-007",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Aleph Doha Residences, Curio Collection by Hilton",
      "Category": "Hotel / Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Short Stay",
      "Season": "All Year",
      "Valid Dates": "01 Jan 2026 – 31 Dec 2026",
      "Season Start": "2026-01-01",
      "Season End": "2026-12-31",
      "Room Type": "Sky Two Bedroom with Maids Room City View",
      "Bedrooms": 2,
      "View": "City View",
      "Single Occupancy Rate QAR": 1150,
      "Double Occupancy Rate QAR": 1200,
      "Daily Rate QAR": 1150,
      "Rate Basis": "Per room, per night; transient business travel only up to 9 rooms/night",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Breakfast; 0% VAT subject to change; no commission; daily housekeeping for short stays; 24-hour maintenance and room service; gym access on 1st floor; indoor pool access on 52nd floor; all rooms subject to availability; confidential corporate rate; not valid for conference/group events or city-wide congresses/events.",
      "Additional Information / Amenities Notes": "Also includes a negotiated 10% discount off Best Available Rate for all available room types where applicable. Lunch supplement QAR 75 per person; dinner supplement QAR 75 per person; airport supplement QAR 140 per way.",
      "Supplements / Blackouts": "Eid El Fitr 19–28 Mar 2026: +QAR 250/night; Eid El Adha 25–30 May 2026: +QAR 250/night; Formula 1 26 Nov–01 Dec 2026: +QAR 350/night.",
      "Cancellation Policy": "Until 6:00 PM on arrival date: no charge. After 6:00 PM on arrival date or no-show: first night room rate plus applicable tax. House policy may change with 60 days' notice.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "Guest settles bill upon departure unless company credit/direct billing has been separately established. Payment terms may be net 30 where company credit applies.",
      "Reservation Method": "Direct to hotel",
      "Contact Name": "Reservations Team",
      "Contact Email": "Reservations.DOHAR@hilton.com",
      "Contact Phone": "+974 400 47 400",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 7,
      "Booking / Display Notes": "Verify final availability, taxes, blackout supplements, and booking requirements with the hotel before confirmation.",
      "Internal Notes": "Daily short-stay rows only. Long-stay monthly/yearly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Aleph Doha Residences (2).pdf, pp. 1-3"
    },
    {
      "Record ID": "CAT-008",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Aleph Doha Residences, Curio Collection by Hilton",
      "Category": "Hotel / Serviced Apartment",
      "Area": "West Bay",
      "Address": "Aba Al Hanin Bil Hanin Street, West Bay, Doha, Qatar, PO Box 24767",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Short Stay",
      "Season": "All Year",
      "Valid Dates": "01 Jan 2026 – 31 Dec 2026",
      "Season Start": "2026-01-01",
      "Season End": "2026-12-31",
      "Room Type": "Sky Two Bedroom with Maids Room Sea View",
      "Bedrooms": 2,
      "View": "Sea View",
      "Single Occupancy Rate QAR": 1200,
      "Double Occupancy Rate QAR": 1250,
      "Daily Rate QAR": 1200,
      "Rate Basis": "Per room, per night; transient business travel only up to 9 rooms/night",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Breakfast; 0% VAT subject to change; no commission; daily housekeeping for short stays; 24-hour maintenance and room service; gym access on 1st floor; indoor pool access on 52nd floor; all rooms subject to availability; confidential corporate rate; not valid for conference/group events or city-wide congresses/events.",
      "Additional Information / Amenities Notes": "Also includes a negotiated 10% discount off Best Available Rate for all available room types where applicable. Lunch supplement QAR 75 per person; dinner supplement QAR 75 per person; airport supplement QAR 140 per way.",
      "Supplements / Blackouts": "Eid El Fitr 19–28 Mar 2026: +QAR 250/night; Eid El Adha 25–30 May 2026: +QAR 250/night; Formula 1 26 Nov–01 Dec 2026: +QAR 350/night.",
      "Cancellation Policy": "Until 6:00 PM on arrival date: no charge. After 6:00 PM on arrival date or no-show: first night room rate plus applicable tax. House policy may change with 60 days' notice.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "Guest settles bill upon departure unless company credit/direct billing has been separately established. Payment terms may be net 30 where company credit applies.",
      "Reservation Method": "Direct to hotel",
      "Contact Name": "Reservations Team",
      "Contact Email": "Reservations.DOHAR@hilton.com",
      "Contact Phone": "+974 400 47 400",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 8,
      "Booking / Display Notes": "Verify final availability, taxes, blackout supplements, and booking requirements with the hotel before confirmation.",
      "Internal Notes": "Daily short-stay rows only. Long-stay monthly/yearly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Aleph Doha Residences (2).pdf, pp. 1-3"
    },
    {
      "Record ID": "CAT-009",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Delta Hotels by Marriott City Center Doha",
      "Category": "Hotel",
      "Area": "City Center / West Bay",
      "Address": "Umm Arsaan Street, City Center Doha, Qatar",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Daily Rate",
      "Season": "High Season",
      "Valid Dates": "01 Jan 2026 – 31 May 2026; 20 Sep 2026 – 31 Dec 2026",
      "Season Start": "2026-01-01",
      "Season End": "2026-12-31",
      "Room Type": "Deluxe Room City View",
      "Bedrooms": "",
      "View": "City View",
      "Single Occupancy Rate QAR": 375,
      "Double Occupancy Rate QAR": 425,
      "Daily Rate QAR": 375,
      "Rate Basis": "Corporate daily rate; individual reservations for weekdays and weekends, subject to hotel availability",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Internet; bed and breakfast; access to gym, pool, and Doha Sands beach club; selected room types include lounge access. Goose Lounge benefits may include soft beverages, snacks, pastries, breakfast at Atsuma, light snack/lunch, tea time, light snack/dinner, and limited house beverages.",
      "Additional Information / Amenities Notes": "Kids 0–6 sharing parents' room/bed free on same meal plan; kids 6–12 charged 50% for breakfast/lunch/dinner; 12+ considered adults. Extra adult charge QAR 200 per day with breakfast, maximum 2 adults + 2 kids below 12 per room. Rollaway bed QAR 125/night. Valet parking available free of charge. Outside food delivery is not allowed to rooms; guests collect food at hotel entrance.",
      "Supplements / Blackouts": "Blackout/special event periods include Web Summit 01–04 Feb 2026, Eid Al Fitr 2026 (3 days), Milipol Qatar 2026, and Formula 1 2026. Rates are based on NLRA and may be subject to restrictions/minimum stay policies.",
      "Cancellation Policy": "Reservations may be cancelled 24 hours before arrival without penalty. Different cancellation terms may apply during certain periods. Late cancellation or no-show may be charged one-night stay.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "All guestroom charges, taxes, and incidentals are the responsibility of the individual traveler unless direct billing or third-party/pre-pay credit card is arranged before arrival.",
      "Reservation Method": "Hotel booking channel / GDS instructions if rate is loaded",
      "Contact Name": "Josiane Jabre",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 1,
      "Booking / Display Notes": "Verify availability, blackout restrictions, final taxes, and booking method before confirmation.",
      "Internal Notes": "Daily rate row only. Long-stay/monthly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Delta Hotel Corporate Agreement 2026.pdf, pp. 1-2"
    },
    {
      "Record ID": "CAT-010",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Delta Hotels by Marriott City Center Doha",
      "Category": "Hotel",
      "Area": "City Center / West Bay",
      "Address": "Umm Arsaan Street, City Center Doha, Qatar",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Daily Rate",
      "Season": "High Season",
      "Valid Dates": "01 Jan 2026 – 31 May 2026; 20 Sep 2026 – 31 Dec 2026",
      "Season Start": "2026-01-01",
      "Season End": "2026-12-31",
      "Room Type": "Deluxe Room Sea View",
      "Bedrooms": "",
      "View": "Sea View",
      "Single Occupancy Rate QAR": 425,
      "Double Occupancy Rate QAR": 475,
      "Daily Rate QAR": 425,
      "Rate Basis": "Corporate daily rate; individual reservations for weekdays and weekends, subject to hotel availability",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Internet; bed and breakfast; access to gym, pool, and Doha Sands beach club; selected room types include lounge access. Goose Lounge benefits may include soft beverages, snacks, pastries, breakfast at Atsuma, light snack/lunch, tea time, light snack/dinner, and limited house beverages.",
      "Additional Information / Amenities Notes": "Kids 0–6 sharing parents' room/bed free on same meal plan; kids 6–12 charged 50% for breakfast/lunch/dinner; 12+ considered adults. Extra adult charge QAR 200 per day with breakfast, maximum 2 adults + 2 kids below 12 per room. Rollaway bed QAR 125/night. Valet parking available free of charge. Outside food delivery is not allowed to rooms; guests collect food at hotel entrance.",
      "Supplements / Blackouts": "Blackout/special event periods include Web Summit 01–04 Feb 2026, Eid Al Fitr 2026 (3 days), Milipol Qatar 2026, and Formula 1 2026. Rates are based on NLRA and may be subject to restrictions/minimum stay policies.",
      "Cancellation Policy": "Reservations may be cancelled 24 hours before arrival without penalty. Different cancellation terms may apply during certain periods. Late cancellation or no-show may be charged one-night stay.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "All guestroom charges, taxes, and incidentals are the responsibility of the individual traveler unless direct billing or third-party/pre-pay credit card is arranged before arrival.",
      "Reservation Method": "Hotel booking channel / GDS instructions if rate is loaded",
      "Contact Name": "Josiane Jabre",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 2,
      "Booking / Display Notes": "Verify availability, blackout restrictions, final taxes, and booking method before confirmation.",
      "Internal Notes": "Daily rate row only. Long-stay/monthly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Delta Hotel Corporate Agreement 2026.pdf, pp. 1-2"
    },
    {
      "Record ID": "CAT-011",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Delta Hotels by Marriott City Center Doha",
      "Category": "Hotel",
      "Area": "City Center / West Bay",
      "Address": "Umm Arsaan Street, City Center Doha, Qatar",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Daily Rate",
      "Season": "High Season",
      "Valid Dates": "01 Jan 2026 – 31 May 2026; 20 Sep 2026 – 31 Dec 2026",
      "Season Start": "2026-01-01",
      "Season End": "2026-12-31",
      "Room Type": "Superior Sea View Room (Includes Lounge Access)",
      "Bedrooms": "",
      "View": "Sea View",
      "Single Occupancy Rate QAR": 500,
      "Double Occupancy Rate QAR": 600,
      "Daily Rate QAR": 500,
      "Rate Basis": "Corporate daily rate; individual reservations for weekdays and weekends, subject to hotel availability",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Internet; bed and breakfast; access to gym, pool, and Doha Sands beach club; selected room types include lounge access. Goose Lounge benefits may include soft beverages, snacks, pastries, breakfast at Atsuma, light snack/lunch, tea time, light snack/dinner, and limited house beverages.",
      "Additional Information / Amenities Notes": "Kids 0–6 sharing parents' room/bed free on same meal plan; kids 6–12 charged 50% for breakfast/lunch/dinner; 12+ considered adults. Extra adult charge QAR 200 per day with breakfast, maximum 2 adults + 2 kids below 12 per room. Rollaway bed QAR 125/night. Valet parking available free of charge. Outside food delivery is not allowed to rooms; guests collect food at hotel entrance. Includes lounge access.",
      "Supplements / Blackouts": "Blackout/special event periods include Web Summit 01–04 Feb 2026, Eid Al Fitr 2026 (3 days), Milipol Qatar 2026, and Formula 1 2026. Rates are based on NLRA and may be subject to restrictions/minimum stay policies.",
      "Cancellation Policy": "Reservations may be cancelled 24 hours before arrival without penalty. Different cancellation terms may apply during certain periods. Late cancellation or no-show may be charged one-night stay.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "All guestroom charges, taxes, and incidentals are the responsibility of the individual traveler unless direct billing or third-party/pre-pay credit card is arranged before arrival.",
      "Reservation Method": "Hotel booking channel / GDS instructions if rate is loaded",
      "Contact Name": "Josiane Jabre",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 3,
      "Booking / Display Notes": "Verify availability, blackout restrictions, final taxes, and booking method before confirmation.",
      "Internal Notes": "Daily rate row only. Long-stay/monthly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Delta Hotel Corporate Agreement 2026.pdf, pp. 1-2"
    },
    {
      "Record ID": "CAT-012",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Delta Hotels by Marriott City Center Doha",
      "Category": "Hotel",
      "Area": "City Center / West Bay",
      "Address": "Umm Arsaan Street, City Center Doha, Qatar",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Daily Rate",
      "Season": "High Season",
      "Valid Dates": "01 Jan 2026 – 31 May 2026; 20 Sep 2026 – 31 Dec 2026",
      "Season Start": "2026-01-01",
      "Season End": "2026-12-31",
      "Room Type": "Junior Suite (Includes Lounge Access)",
      "Bedrooms": "",
      "View": "Suite",
      "Single Occupancy Rate QAR": 685,
      "Double Occupancy Rate QAR": 785,
      "Daily Rate QAR": 685,
      "Rate Basis": "Corporate daily rate; individual reservations for weekdays and weekends, subject to hotel availability",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Internet; bed and breakfast; access to gym, pool, and Doha Sands beach club; selected room types include lounge access. Goose Lounge benefits may include soft beverages, snacks, pastries, breakfast at Atsuma, light snack/lunch, tea time, light snack/dinner, and limited house beverages.",
      "Additional Information / Amenities Notes": "Kids 0–6 sharing parents' room/bed free on same meal plan; kids 6–12 charged 50% for breakfast/lunch/dinner; 12+ considered adults. Extra adult charge QAR 200 per day with breakfast, maximum 2 adults + 2 kids below 12 per room. Rollaway bed QAR 125/night. Valet parking available free of charge. Outside food delivery is not allowed to rooms; guests collect food at hotel entrance. Includes lounge access.",
      "Supplements / Blackouts": "Blackout/special event periods include Web Summit 01–04 Feb 2026, Eid Al Fitr 2026 (3 days), Milipol Qatar 2026, and Formula 1 2026. Rates are based on NLRA and may be subject to restrictions/minimum stay policies.",
      "Cancellation Policy": "Reservations may be cancelled 24 hours before arrival without penalty. Different cancellation terms may apply during certain periods. Late cancellation or no-show may be charged one-night stay.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "All guestroom charges, taxes, and incidentals are the responsibility of the individual traveler unless direct billing or third-party/pre-pay credit card is arranged before arrival.",
      "Reservation Method": "Hotel booking channel / GDS instructions if rate is loaded",
      "Contact Name": "Josiane Jabre",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 4,
      "Booking / Display Notes": "Verify availability, blackout restrictions, final taxes, and booking method before confirmation.",
      "Internal Notes": "Daily rate row only. Long-stay/monthly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Delta Hotel Corporate Agreement 2026.pdf, pp. 1-2"
    },
    {
      "Record ID": "CAT-013",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Delta Hotels by Marriott City Center Doha",
      "Category": "Hotel",
      "Area": "City Center / West Bay",
      "Address": "Umm Arsaan Street, City Center Doha, Qatar",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Daily Rate",
      "Season": "High Season",
      "Valid Dates": "01 Jan 2026 – 31 May 2026; 20 Sep 2026 – 31 Dec 2026",
      "Season Start": "2026-01-01",
      "Season End": "2026-12-31",
      "Room Type": "One-Bedroom Suite (Includes Lounge Access)",
      "Bedrooms": 1,
      "View": "Suite",
      "Single Occupancy Rate QAR": 785,
      "Double Occupancy Rate QAR": 685,
      "Daily Rate QAR": 785,
      "Rate Basis": "Corporate daily rate; individual reservations for weekdays and weekends, subject to hotel availability",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Internet; bed and breakfast; access to gym, pool, and Doha Sands beach club; selected room types include lounge access. Goose Lounge benefits may include soft beverages, snacks, pastries, breakfast at Atsuma, light snack/lunch, tea time, light snack/dinner, and limited house beverages.",
      "Additional Information / Amenities Notes": "Kids 0–6 sharing parents' room/bed free on same meal plan; kids 6–12 charged 50% for breakfast/lunch/dinner; 12+ considered adults. Extra adult charge QAR 200 per day with breakfast, maximum 2 adults + 2 kids below 12 per room. Rollaway bed QAR 125/night. Valet parking available free of charge. Outside food delivery is not allowed to rooms; guests collect food at hotel entrance. Includes lounge access. Verify DBL rate because contract image appears to show DBL lower than SNG.",
      "Supplements / Blackouts": "Blackout/special event periods include Web Summit 01–04 Feb 2026, Eid Al Fitr 2026 (3 days), Milipol Qatar 2026, and Formula 1 2026. Rates are based on NLRA and may be subject to restrictions/minimum stay policies.",
      "Cancellation Policy": "Reservations may be cancelled 24 hours before arrival without penalty. Different cancellation terms may apply during certain periods. Late cancellation or no-show may be charged one-night stay.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "All guestroom charges, taxes, and incidentals are the responsibility of the individual traveler unless direct billing or third-party/pre-pay credit card is arranged before arrival.",
      "Reservation Method": "Hotel booking channel / GDS instructions if rate is loaded",
      "Contact Name": "Josiane Jabre",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 5,
      "Booking / Display Notes": "Verify availability, blackout restrictions, final taxes, and booking method before confirmation.",
      "Internal Notes": "Daily rate row only. Long-stay/monthly rates intentionally excluded. Verify Delta high-season One-Bedroom Suite DBL rate from contract image.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Delta Hotel Corporate Agreement 2026.pdf, pp. 1-2"
    },
    {
      "Record ID": "CAT-014",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Delta Hotels by Marriott City Center Doha",
      "Category": "Hotel",
      "Area": "City Center / West Bay",
      "Address": "Umm Arsaan Street, City Center Doha, Qatar",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Daily Rate",
      "Season": "Low Season",
      "Valid Dates": "01 Jun 2026 – 19 Sep 2026",
      "Season Start": "2026-06-01",
      "Season End": "2026-09-19",
      "Room Type": "Deluxe Room City View",
      "Bedrooms": "",
      "View": "City View",
      "Single Occupancy Rate QAR": 335,
      "Double Occupancy Rate QAR": 385,
      "Daily Rate QAR": 335,
      "Rate Basis": "Corporate daily rate; individual reservations for weekdays and weekends, subject to hotel availability",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Internet; bed and breakfast; access to gym, pool, and Doha Sands beach club; selected room types include lounge access. Goose Lounge benefits may include soft beverages, snacks, pastries, breakfast at Atsuma, light snack/lunch, tea time, light snack/dinner, and limited house beverages.",
      "Additional Information / Amenities Notes": "Kids 0–6 sharing parents' room/bed free on same meal plan; kids 6–12 charged 50% for breakfast/lunch/dinner; 12+ considered adults. Extra adult charge QAR 200 per day with breakfast, maximum 2 adults + 2 kids below 12 per room. Rollaway bed QAR 125/night. Valet parking available free of charge. Outside food delivery is not allowed to rooms; guests collect food at hotel entrance.",
      "Supplements / Blackouts": "Blackout/special event periods include Web Summit 01–04 Feb 2026, Eid Al Fitr 2026 (3 days), Milipol Qatar 2026, and Formula 1 2026. Rates are based on NLRA and may be subject to restrictions/minimum stay policies.",
      "Cancellation Policy": "Reservations may be cancelled 24 hours before arrival without penalty. Different cancellation terms may apply during certain periods. Late cancellation or no-show may be charged one-night stay.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "All guestroom charges, taxes, and incidentals are the responsibility of the individual traveler unless direct billing or third-party/pre-pay credit card is arranged before arrival.",
      "Reservation Method": "Hotel booking channel / GDS instructions if rate is loaded",
      "Contact Name": "Josiane Jabre",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 11,
      "Booking / Display Notes": "Verify availability, blackout restrictions, final taxes, and booking method before confirmation.",
      "Internal Notes": "Daily rate row only. Long-stay/monthly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Delta Hotel Corporate Agreement 2026.pdf, pp. 1-2"
    },
    {
      "Record ID": "CAT-015",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Delta Hotels by Marriott City Center Doha",
      "Category": "Hotel",
      "Area": "City Center / West Bay",
      "Address": "Umm Arsaan Street, City Center Doha, Qatar",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Daily Rate",
      "Season": "Low Season",
      "Valid Dates": "01 Jun 2026 – 19 Sep 2026",
      "Season Start": "2026-06-01",
      "Season End": "2026-09-19",
      "Room Type": "Deluxe Room Sea View",
      "Bedrooms": "",
      "View": "Sea View",
      "Single Occupancy Rate QAR": 385,
      "Double Occupancy Rate QAR": 435,
      "Daily Rate QAR": 385,
      "Rate Basis": "Corporate daily rate; individual reservations for weekdays and weekends, subject to hotel availability",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Internet; bed and breakfast; access to gym, pool, and Doha Sands beach club; selected room types include lounge access. Goose Lounge benefits may include soft beverages, snacks, pastries, breakfast at Atsuma, light snack/lunch, tea time, light snack/dinner, and limited house beverages.",
      "Additional Information / Amenities Notes": "Kids 0–6 sharing parents' room/bed free on same meal plan; kids 6–12 charged 50% for breakfast/lunch/dinner; 12+ considered adults. Extra adult charge QAR 200 per day with breakfast, maximum 2 adults + 2 kids below 12 per room. Rollaway bed QAR 125/night. Valet parking available free of charge. Outside food delivery is not allowed to rooms; guests collect food at hotel entrance.",
      "Supplements / Blackouts": "Blackout/special event periods include Web Summit 01–04 Feb 2026, Eid Al Fitr 2026 (3 days), Milipol Qatar 2026, and Formula 1 2026. Rates are based on NLRA and may be subject to restrictions/minimum stay policies.",
      "Cancellation Policy": "Reservations may be cancelled 24 hours before arrival without penalty. Different cancellation terms may apply during certain periods. Late cancellation or no-show may be charged one-night stay.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "All guestroom charges, taxes, and incidentals are the responsibility of the individual traveler unless direct billing or third-party/pre-pay credit card is arranged before arrival.",
      "Reservation Method": "Hotel booking channel / GDS instructions if rate is loaded",
      "Contact Name": "Josiane Jabre",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 12,
      "Booking / Display Notes": "Verify availability, blackout restrictions, final taxes, and booking method before confirmation.",
      "Internal Notes": "Daily rate row only. Long-stay/monthly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Delta Hotel Corporate Agreement 2026.pdf, pp. 1-2"
    },
    {
      "Record ID": "CAT-016",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Delta Hotels by Marriott City Center Doha",
      "Category": "Hotel",
      "Area": "City Center / West Bay",
      "Address": "Umm Arsaan Street, City Center Doha, Qatar",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Daily Rate",
      "Season": "Low Season",
      "Valid Dates": "01 Jun 2026 – 19 Sep 2026",
      "Season Start": "2026-06-01",
      "Season End": "2026-09-19",
      "Room Type": "Superior Sea View Room (Includes Lounge Access)",
      "Bedrooms": "",
      "View": "Sea View",
      "Single Occupancy Rate QAR": 465,
      "Double Occupancy Rate QAR": 565,
      "Daily Rate QAR": 465,
      "Rate Basis": "Corporate daily rate; individual reservations for weekdays and weekends, subject to hotel availability",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Internet; bed and breakfast; access to gym, pool, and Doha Sands beach club; selected room types include lounge access. Goose Lounge benefits may include soft beverages, snacks, pastries, breakfast at Atsuma, light snack/lunch, tea time, light snack/dinner, and limited house beverages.",
      "Additional Information / Amenities Notes": "Kids 0–6 sharing parents' room/bed free on same meal plan; kids 6–12 charged 50% for breakfast/lunch/dinner; 12+ considered adults. Extra adult charge QAR 200 per day with breakfast, maximum 2 adults + 2 kids below 12 per room. Rollaway bed QAR 125/night. Valet parking available free of charge. Outside food delivery is not allowed to rooms; guests collect food at hotel entrance. Includes lounge access.",
      "Supplements / Blackouts": "Blackout/special event periods include Web Summit 01–04 Feb 2026, Eid Al Fitr 2026 (3 days), Milipol Qatar 2026, and Formula 1 2026. Rates are based on NLRA and may be subject to restrictions/minimum stay policies.",
      "Cancellation Policy": "Reservations may be cancelled 24 hours before arrival without penalty. Different cancellation terms may apply during certain periods. Late cancellation or no-show may be charged one-night stay.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "All guestroom charges, taxes, and incidentals are the responsibility of the individual traveler unless direct billing or third-party/pre-pay credit card is arranged before arrival.",
      "Reservation Method": "Hotel booking channel / GDS instructions if rate is loaded",
      "Contact Name": "Josiane Jabre",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 13,
      "Booking / Display Notes": "Verify availability, blackout restrictions, final taxes, and booking method before confirmation.",
      "Internal Notes": "Daily rate row only. Long-stay/monthly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Delta Hotel Corporate Agreement 2026.pdf, pp. 1-2"
    },
    {
      "Record ID": "CAT-017",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Delta Hotels by Marriott City Center Doha",
      "Category": "Hotel",
      "Area": "City Center / West Bay",
      "Address": "Umm Arsaan Street, City Center Doha, Qatar",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Daily Rate",
      "Season": "Low Season",
      "Valid Dates": "01 Jun 2026 – 19 Sep 2026",
      "Season Start": "2026-06-01",
      "Season End": "2026-09-19",
      "Room Type": "Junior Suite (Includes Lounge Access)",
      "Bedrooms": "",
      "View": "Suite",
      "Single Occupancy Rate QAR": 585,
      "Double Occupancy Rate QAR": 685,
      "Daily Rate QAR": 585,
      "Rate Basis": "Corporate daily rate; individual reservations for weekdays and weekends, subject to hotel availability",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Internet; bed and breakfast; access to gym, pool, and Doha Sands beach club; selected room types include lounge access. Goose Lounge benefits may include soft beverages, snacks, pastries, breakfast at Atsuma, light snack/lunch, tea time, light snack/dinner, and limited house beverages.",
      "Additional Information / Amenities Notes": "Kids 0–6 sharing parents' room/bed free on same meal plan; kids 6–12 charged 50% for breakfast/lunch/dinner; 12+ considered adults. Extra adult charge QAR 200 per day with breakfast, maximum 2 adults + 2 kids below 12 per room. Rollaway bed QAR 125/night. Valet parking available free of charge. Outside food delivery is not allowed to rooms; guests collect food at hotel entrance. Includes lounge access.",
      "Supplements / Blackouts": "Blackout/special event periods include Web Summit 01–04 Feb 2026, Eid Al Fitr 2026 (3 days), Milipol Qatar 2026, and Formula 1 2026. Rates are based on NLRA and may be subject to restrictions/minimum stay policies.",
      "Cancellation Policy": "Reservations may be cancelled 24 hours before arrival without penalty. Different cancellation terms may apply during certain periods. Late cancellation or no-show may be charged one-night stay.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "All guestroom charges, taxes, and incidentals are the responsibility of the individual traveler unless direct billing or third-party/pre-pay credit card is arranged before arrival.",
      "Reservation Method": "Hotel booking channel / GDS instructions if rate is loaded",
      "Contact Name": "Josiane Jabre",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 14,
      "Booking / Display Notes": "Verify availability, blackout restrictions, final taxes, and booking method before confirmation.",
      "Internal Notes": "Daily rate row only. Long-stay/monthly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Delta Hotel Corporate Agreement 2026.pdf, pp. 1-2"
    },
    {
      "Record ID": "CAT-018",
      "Approval Status": "Approved",
      "Catalogue Visibility": "Internal",
      "Property Name": "Delta Hotels by Marriott City Center Doha",
      "Category": "Hotel",
      "Area": "City Center / West Bay",
      "Address": "Umm Arsaan Street, City Center Doha, Qatar",
      "Agreement Start": "2026-01-01",
      "Agreement End": "2026-12-31",
      "Stay Type": "Daily Rate",
      "Season": "Low Season",
      "Valid Dates": "01 Jun 2026 – 19 Sep 2026",
      "Season Start": "2026-06-01",
      "Season End": "2026-09-19",
      "Room Type": "One-Bedroom Suite (Includes Lounge Access)",
      "Bedrooms": 1,
      "View": "Suite",
      "Single Occupancy Rate QAR": 685,
      "Double Occupancy Rate QAR": 785,
      "Daily Rate QAR": 685,
      "Rate Basis": "Corporate daily rate; individual reservations for weekdays and weekends, subject to hotel availability",
      "Currency": "QAR",
      "Breakfast Included": "Yes",
      "Amenities / Inclusions": "Internet; bed and breakfast; access to gym, pool, and Doha Sands beach club; selected room types include lounge access. Goose Lounge benefits may include soft beverages, snacks, pastries, breakfast at Atsuma, light snack/lunch, tea time, light snack/dinner, and limited house beverages.",
      "Additional Information / Amenities Notes": "Kids 0–6 sharing parents' room/bed free on same meal plan; kids 6–12 charged 50% for breakfast/lunch/dinner; 12+ considered adults. Extra adult charge QAR 200 per day with breakfast, maximum 2 adults + 2 kids below 12 per room. Rollaway bed QAR 125/night. Valet parking available free of charge. Outside food delivery is not allowed to rooms; guests collect food at hotel entrance. Includes lounge access.",
      "Supplements / Blackouts": "Blackout/special event periods include Web Summit 01–04 Feb 2026, Eid Al Fitr 2026 (3 days), Milipol Qatar 2026, and Formula 1 2026. Rates are based on NLRA and may be subject to restrictions/minimum stay policies.",
      "Cancellation Policy": "Reservations may be cancelled 24 hours before arrival without penalty. Different cancellation terms may apply during certain periods. Late cancellation or no-show may be charged one-night stay.",
      "Check-In": "3:00 PM",
      "Check-Out": "12:00 PM",
      "Payment / Billing": "All guestroom charges, taxes, and incidentals are the responsibility of the individual traveler unless direct billing or third-party/pre-pay credit card is arranged before arrival.",
      "Reservation Method": "Hotel booking channel / GDS instructions if rate is loaded",
      "Contact Name": "Josiane Jabre",
      "Contact Email": "",
      "Contact Phone": "",
      "Website URL": "",
      "Virtual Tour URL": "",
      "Flyer URL": "",
      "Image URL": "",
      "Gallery URLs": "",
      "Room Detail URL": "",
      "Room Video URL": "",
      "Room Image URL": "",
      "Unit Display Order": 15,
      "Booking / Display Notes": "Verify availability, blackout restrictions, final taxes, and booking method before confirmation.",
      "Internal Notes": "Daily rate row only. Long-stay/monthly rates intentionally excluded.",
      "Last Updated": "2026-06-10",
      "Source Contract": "Delta Hotel Corporate Agreement 2026.pdf, pp. 1-2"
    }
  ]
};
